language: node_js
node_js: "stable"

#cache:
#  directories:
#    - node_modules

dist: trusty

script:
  - npm install -g qxcompiler
  - qx compile --target=build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build-output
  on:
    branch: master
