language: node_js
node_js: "stable"

#cache:
#  directories:
#    - node_modules

dist: trusty

install:
  - npm install -g qxcompiler
  - git clone --depth 1 https://github.com/qooxdoo/qooxdoo.git qooxdoo
  - qx config set qx.library qooxdoo

script:
  - qx compile --target=build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build-output
  on:
    branch: master
