language: node_js
node_js: "stable"

#cache:
#  directories:
#    - node_modules

dist: trusty

install:
  - npm install -g qxcompiler
  # use qooxdoo master for the moment, this will be replaced with npm packages
  - git clone --depth 1 https://github.com/qooxdoo/qooxdoo.git qooxdoo
  - qx config set qx.library qooxdoo

script:
  - qx serve --target=build &
  - npx testcafe chrome,firefox tests/testcafe.js  --app-init-delay 10000

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build-output
  on:
    branch: master
