language: node_js
node_js: "10"

dist: trusty

env:
  - QX_TARGET=build

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable fluxbox

before_install:
  - stty cols 80

install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - npm install -g @qooxdoo/compiler
#  - qx config set github.token $GITHUB_TOKEN
#  - qx pkg update
  - qx pkg install

script:
  - tests/test-travis.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: compiled/$QX_TARGET
  on:
    branch: master
