language: node_js
node_js: "8"

dist: trusty

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
#    packages:
#      - google-chrome-stable fluxbox

before_install:
  - stty cols 80

install:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3
#  - fluxbox >/dev/null 2>&1 &
  - npm install -g qxcompiler
  - qx config set github.token $GITHUB_TOKEN
  - qx contrib update
  - qx contrib install

script:
  - tests/test-travis.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: compiled/build
  on:
    branch: master
